---
- hosts: all
  become: yes
  tasks:
    - name: Update the server
      yum:
        name: "*"
        state: latest

    - name: Install required packages (Python3, MySQL)
      yum:
        name:
          - python3
          - python3-pip
          - mysql-server
        state: present

    - name: Start MySQL service
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: Install Python dependencies
      pip:
        name:
          - flask
          - flask-mysql
        state: present
    
    - name: Install Prometheus
      get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.30.3/prometheus-2.30.3.linux-amd64.tar.gz
        dest: /tmp/prometheus.tar.gz

    - name: Extract Prometheus
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Configure Prometheus
      copy:
        dest: /opt/prometheus-2.30.3.linux-amd64/prometheus.yml
        content: |
          global:
            scrape_interval: 15s

          scrape_configs:
            - job_name: 'flask-app'
              static_configs:
                - targets: ['localhost:5000']

    - name: Start Prometheus
      shell: |
        nohup /opt/prometheus-2.30.3.linux-amd64/prometheus --config.file=/opt/prometheus-2.30.3.linux-amd64/prometheus.yml &

    - name: Clone Bookstore API Repository
      git:
        repo: 'https://github.com/AhmetBasari/Jenkins-ansible-bookstore-api-on-python-flask-mysql.git'
        dest: /home/ec2-user/bookstore-api

    - name: Start the Bookstore API
      shell: |
        nohup python3 /home/ec2-user/bookstore-api/bookstore-api.py &
      args:
        chdir: /home/ec2-user/bookstore-api
